# Generated by Django 3.2.5 on 2021-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
