# Generated by Django 3.2.4 on 2021-06-24 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparison', '0002_auto_20210623_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinfo',
            options={'verbose_name_plural': 'Additional Info'},
        ),
    ]
