# Generated by Django 3.2.5 on 2021-07-05 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparison', '0004_auto_20210626_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uodated_at',
            new_name='updated_at',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=3000, null=True)),
                ('name', models.CharField(max_length=160)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='price_comparison.product')),
            ],
            options={
                'ordering': ['last_update'],
            },
        ),
    ]
