# Generated by Django 3.2.5 on 2021-07-05 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparison', '0005_auto_20210704_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['last_update'], 'verbose_name_plural': 'Comments'},
        ),
    ]
