# Generated by Django 3.2.5 on 2021-07-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_comparison', '0006_alter_comments_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment',
        ),
    ]
