# Generated by Django 3.2.4 on 2021-07-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
