# Generated by Django 3.2.4 on 2021-07-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_comments_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_slug',
        ),
    ]
