# Generated by Django 3.2.4 on 2021-07-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_comments_comment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_slug',
            field=models.SlugField(default=1, max_length=3000),
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(default=1, max_length=3000),
        ),
    ]
