# Generated by Django 3.2.4 on 2021-07-10 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210710_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_slug',
            field=models.CharField(default=1, max_length=3000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.CharField(default=1, max_length=3000),
        ),
    ]
