# Generated by Django 3.2.4 on 2021-07-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
