# Generated by Django 3.2.5 on 2021-07-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
