# Generated by Django 3.2.4 on 2021-07-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_comments_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='product_id',
            new_name='product',
        ),
    ]
