# Generated by Django 3.2.4 on 2021-07-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
    ]
