# Generated by Django 3.2.5 on 2021-08-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='text', max_length=3000),
            preserve_default=False,
        ),
    ]
