# Generated by Django 3.2.5 on 2021-07-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210705_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
