# Generated by Django 3.2.5 on 2021-07-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210705_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['last_update'], 'verbose_name': 'Comments'},
        ),
    ]
