# Generated by Django 3.2.4 on 2021-07-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210715_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebay_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=None, default=True),
        ),
    ]
