# Generated by Django 3.2.4 on 2021-07-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210715_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amazon_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebay_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=100),
        ),
    ]
